name: Proxy Checker

on:
  schedule:
    - cron: '0 */12 * * *' # run every 12 hours

jobs:
  get_proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download the subscription file(s)
      - name: Download Proxy Subscriptions
        id: download_subscriptions
        run: |
          SUBSCRIPTIONS=(
            "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt"
            "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/data/all.txt"
          )
          for SUB in "${SUBSCRIPTIONS[@]}"; do
            curl -L -o "${{ github.workspace }}/${{ hashFiles(SUB) }}.txt" "$SUB"
          done

      # Merge and filter the proxy files
      - name: Merge and Filter Proxy Files
        id: filter_proxies
        run: |
          # Concatenate all the subscription files
          cat "${{ github.workspace }}/*.txt" > "${{ github.workspace }}/all_proxies.txt"

          # Sort and filter out duplicates
          sort -u "${{ github.workspace }}/all_proxies.txt" > "${{ github.workspace }}/filtered_proxies.txt"

      # Publish filtered proxies as an artifact
      - name: Publish Filtered Proxies
        uses: actions/upload-artifact@v2
        with:
          name: filtered_proxies
          path: ${{ github.workspace }}/filtered_proxies.txt
